### ISSUE TITLE
[HELP] Can I dynamatically loading components and system?

### ISSUE THREAD

**Issue by linonetwo** [JaimeGensler/thyseus#2]
**What do you need help with?**

I want to load mod from the web, using technique from https://2ality.com/2019/10/eval-via-import.html

Is this possible in thyseus? Will dynamically loaded JS that includes some component or system still work?

**Comment by JaimeGensler** [comment]
Hey there! Thanks for your interest in Thyseus.

Components and systems cannot be added to a `World` _after_ building, but a `WorldBuilder` has no way of knowing if the components/systems it's given were loaded dynamically or not, so dynamically loaded chunks (or dynamically loading the `WorldBuilder`/`World` itself) are totally fine. If this is what you're looking for, this is definitely possible in Thyseus!

If you want to add components/systems _after_ building, Thyseus does not support this. You can work around this by using multiple worlds (e.g. a "menu world" which handles selection of any potential plugins, and the actual game world which is built from those plugins). You could also technically re-build a world with the newly added components/systems, although I would probably advise against this approach.

I hope that answers your questions, and let me know if you need anything else! 😄

**Comment by linonetwo** [comment]
Thanks! this includes all the information I need.
