### ISSUE TITLE
[BUG] Typescript return type for vite in rollup-plugin-thyseus incorrect

### ISSUE THREAD

**Issue by DanielBelmes** [JaimeGensler/thyseus#70]
## Bug Description

When viewing vite plugin config. The Thyseus() return type is being flagged as an incompatible type. From looking at other rollup vite compatible plugins. Most seem to use return type Plugin from 'rollup'

### Thyseus Version

HEAD

### Bundler / Build Tool

Vite, pnpm

### Environment & Version

Vscode

### Reproduction Repo (optional)

Just create a new folder with the create thyseus template

**Comment by JaimeGensler** [comment]
Thanks for the report 🙏 goofy I managed to miss this, should be a simple fix. Will cut a new version as soon as it's resolved!
