### ISSUE TITLE
[BUG] vite won't build top level async await from template

### ISSUE THREAD

**Issue by DanielBelmes** [JaimeGensler/thyseus#71]
## Bug Description

Vite won't build template file as it doesn't target the build for esnext

### Bundler / Build Tool

Vite, pnpm

### Environment & Version

cli

### Reproduction Repo (optional)

vite build the template

**Comment by DanielBelmes** [comment]
```build:{
		target: "esnext" // or "es2019",
	   }```
	   
	   I added this to the config to get it to build

**Comment by JaimeGensler** [comment]
Thanks for the report!
Just for clarity, you're referring to the template created from using `pnpm create thyseus`?

**Comment by DanielBelmes** [comment]
Yup! @JaimeGensler Been fun checking the library out! If you have any benchmarks btw I'd love to see them.

**Comment by JaimeGensler** [comment]
Glad you've enjoyed it so far, and thanks for the bug reports! As far as benchmarks, I don't have any formal benches at the moment, it's an eventual goal but it's a lower priority for me at the moment. Contributions on this front always welcome if you're interested!
